[features]
seeds = false
[programs.localnet]
token_plata = "7fQFifcVnr4gkSHwkp21ggCKVSrhLdSccDZ2gdUHoy25"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/p.malyugin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
